# Site settings
title: Haoyang Huang's Homepage
description: Haoyang Huang's Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Haoyang Huang's Homepage
user_description: Huang Haoyang is head of the Multimodal Foundation Models team at JD Discovery Academy, leading research on unified multimodal models. He holds a master's from Peking University, won top domestic data mining awards, and is a Kaggle Master. At Microsoft Research Asia, he focused on multimodal and multilingual foundation models, developing the multilingual model <a href="https://arxiv.org/abs/1909.00964" style="color:blue;">Unicoder</a> (covering 100 languages) and leading the world’s first multilingual multimodal pre-trained model <a href="https://arxiv.org/abs/2006.02635" style="color:blue;">M3P</a>. He has published dozens of papers in CVPR, ACL, EMNLP, AAAI, with 2k+ Google Scholar citations. In 2024, he joined StepFun, leading and open-sourcing the 30B StepVideo series (<a href="https://arxiv.org/abs/2502.10248" style="color:blue;">Step-Video-T2V</a>, <a href="https://arxiv.org/abs/2503.11251" style="color:blue;">Step-Video-TI2V</a>).
user_description2:  黄浩洋现任京东探索学院图像与多模态实验室多模态基础模型团队负责人，带领团队开展统一多模态模型研究。他拥有北京大学硕士学位，曾获得国内顶级数据挖掘奖项，并获得 Kaggle Master 称号。在微软亚洲研究院，他专注于多模态与多语言基础模型，研发了覆盖 100 种语言的多语言模型 Unicoder，并主导了全球首个多语言多模态预训练模型 M3P 的研发。他在 CVPR、ACL、EMNLP、AAAI 等顶级会议发表数十篇论文，谷歌学术引用量超过 2,000 次。2024 年，他加入 StepFun，主导并开源了 30B StepVideo 模型系列（Step-Video-T2V、Step-Video-TI2V）。

user_title: Pioneering multimodal foundation models for AGI.
email: huanghaoyang.ocean@jd.com
# twitter_username: lorem_ipsum
Scholar_username: nIS66toAAAAJ&hl=en
linkedin_username: 浩洋-黄-77a59016a/
github_username:  hhyhhyhy
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum



exclude: ['package.json', 'src', 'node_modules', 'vendor']

